### ISSUE TITLE
header nav de permanecer sin efecto es mejor con sticky

### ISSUE THREAD

**Issue by jeancahu** [fabianabarca/buses#65]
La barra horizontal de navegación en la parte de arriba de la página en su forma para desktop, originalmente viene con la siguiente clase de css.

```css
.header-sticky-top-lg {
    position: fixed;
    bottom: auto;
    top: 0;
}
```
la position de tipo fixed **no** introduce un área en el documento, al igual que el _absolute_ no se posiciona entre los otros elementos, lo que hace que todos los demás elementos ignoren su existencia.

el siguiente elemento en el documento es el _main_ este elemento empieza desde arriba de la página, se traslapa con el topbar porque lo ignora y se muestra por debajo del esta barra. Para evitar esto el creador del tema introdujo un espacio vertical igual al de el alto de la barra al puro inicio de _main_, esto normalmente no se hace así pero el diseñador lo hizo porque él quería que el tema tuviera un efecto en el que la bara se desaparece y aparece conforme se hace scroll hacia abajo o hacia arriba.

Actualmente el efecto ha dejado de funcionar o está desactivado, de dejarlo así entonces ya no tendría sentido mantener el fixed, para evitar tener que dejar ese espacio vacío en _main_ lo mejor sería usar sticky el cual SI posiciona en el documento, obligando a los demás elementos a ordenarse respetando el área de la barra. para esto se podría hacer con la siguiente clase:

```css
.custom-header-sticky-top-lg {
    position: sticky;
    bottom: auto;
    top: 0;
}
```
